#!/bin/bash

echo "🚀 AWS Risk Copilot - Render.com Deployment Guide"
echo "=================================================="
echo ""
echo "📋 PROJECT OVERVIEW:"
echo "• AI Risk Intelligence Platform with RAG"
echo "• Built with FastAPI + Streamlit + Redis"
echo "• Memory optimized: 170MB/1024MB used"
echo "• Cost optimized: $0/month deployment"
echo ""
echo "🎯 RENDER.COM SETUP (3 SERVICES NEEDED):"
echo ""
echo "1. REDIS SERVICE (Key Value Instance)"
echo "   • Type: Key Value Instance"
echo "   • Name: risk-copilot-redis"
echo "   • Plan: Free"
echo "   • Region: Virginia (US East)"
echo ""
echo "2. BACKEND SERVICE (Web Service)"
echo "   • Type: Web Service"
echo "   • Name: risk-copilot-backend"
echo "   • Environment: Docker"
echo "   • Build Command: (leave empty)"
echo "   • Start Command: (leave empty)"
echo "   • Instance: Free"
echo "   • Environment Variables:"
echo "     - PORT=8000"
echo "     - REDIS_URL=redis://risk-copilot-redis:6379"
echo "     - GOOGLE_API_KEY=your_gemini_api_key"
echo "     - NEWSAPI_KEY=your_newsapi_key"
echo "     - FINNHUB_API_KEY=your_finnhub_key"
echo "   • Health Check: /health"
echo ""
echo "3. FRONTEND SERVICE (Web Service)"
echo "   • Type: Web Service"
echo "   • Name: risk-copilot-frontend"
echo "   • Environment: Docker"
echo "   • Build Command: (leave empty)"
echo "   • Start Command: (leave empty)"
echo "   • Instance: Free"
echo "   • Environment Variables:"
echo "     - BACKEND_URL=https://risk-copilot-backend.onrender.com"
echo "     - PORT=8501"
echo "   • Health Check: /_stcore/health"
echo ""
echo "📊 DEPLOYMENT ORDER:"
echo "   1. Create Redis service FIRST"
echo "   2. Create Backend service SECOND"
echo "   3. Create Frontend service LAST"
echo ""
echo "🌐 EXPECTED URLs:"
echo "   • Dashboard: https://risk-copilot-frontend.onrender.com"
echo "   • API: https://risk-copilot-backend.onrender.com"
echo "   • API Docs: https://risk-copilot-backend.onrender.com/docs"
echo ""
echo "✅ AUTO-DEPLOYMENT:"
echo "   Render will auto-deploy on every git push to main branch"
echo ""
echo "🔧 TROUBLESHOOTING:"
echo "   • If backend fails: Check Redis connection"
echo "   • If frontend fails: Check BACKEND_URL"
echo "   • Health checks: Wait 2-3 minutes after deployment"
echo ""
echo "📞 SUPPORT:"
echo "   • GitHub: https://github.com/Harshgitbu/aws-enterprise-risk-copilot"
echo "   • Email: shahharsh0612@gmail.com"
echo ""
echo "💰 COST: $0/month (All services on Free plan)"
